---
- hosts: 172.31.16.93
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: i want to install webserver on ansible node
    apt:
      name: apache2
      state: present 
  - name: i want to copy myindexfile into ansible node side
    template: 
        src: 
        dest: /var/www/html/index.html