---
- hosts: 172.31.16.93
  become: yes
  vars: 
     myvars1: git
     myvars2: tree
     myvars3: wget
  tasks: 
  - name: install tree
    apt: 
      name: "{{myvar1}}"
  - name: i want to display myvar1
    debug:
       msg: "{{myvar1}}"